CREATE DATABASE SBA_ANALYSIS;
USE SBA_ANALYSIS;

SET GLOBAL local_infile = 1;


LOAD DATA LOCAL INFILE 'C:/Users/Aayush/Downloads/SBA dataset_V1.csv'
INTO TABLE sba_data
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;


SHOW GLOBAL VARIABLES LIKE 'local_infile';

DESCRIBE sba_data;

SHOW WARNINGS;



SELECT * FROM sba_DATA;


-- Portfolio Overview

-- Q1. Total Loans
SELECT COUNT(*) FROM SBA_DATA;

-- Q2. Total Loan Amount Disbursed
SELECT SUM(LOAN_AMOUNT_DISBURSED) AS LOAN_DISBURSED FROM SBA_DATA;

-- Q3 Total Bank Approved Amount
SELECT SUM(BANK_APPROVED_AMOUNT) FROM SBA_DATA;

-- Q4 Total SBA Guaranteed Amount
SELECT sum(SBA_GUARANTEED_AMOUNT) FROM SBA_DATA;

-- Q4 Total Charged-Off Principal
SELECT SUM(CHARGED_OFF_PRINCIPAL) FROM SBA_DATA;

-- Q5 Average Loan Amount
SELECT AVG(Bank_Approved_Amount) FROM SBA_DATA;


-- Data Quality Issue inspection (Loan_Amount_Disbursed > Bank_Approved_Amount)
SELECT
    SUM(Loan_Amount_Disbursed) AS Total_Disbursed,
    SUM(Bank_Approved_Amount) AS Total_Bank_Approved
FROM SBA_DATA;


SELECT COUNT(*) FROM SBA_DATA
WHERE LOAN_AMOUNT_DISBURSED > BANK_APPROVED_AMOUNT;

SELECT
    Loan_ID,
    Loan_Amount_Disbursed,
    Bank_Approved_Amount,
    SBA_Guaranteed_Amount,
    Loan_Status
FROM sba_data
WHERE Loan_Amount_Disbursed > Bank_Approved_Amount
LIMIT 20;


SELECT
    COUNT(*) AS Total_Loans,
    SUM(CASE WHEN Loan_Amount_Disbursed > Bank_Approved_Amount THEN 1 ELSE 0 END) AS Greater,
    SUM(CASE WHEN Loan_Amount_Disbursed = Bank_Approved_Amount THEN 1 ELSE 0 END) AS Equal,
    SUM(CASE WHEN Loan_Amount_Disbursed < Bank_Approved_Amount THEN 1 ELSE 0 END) AS Less
FROM sba_data;


SELECT
    MIN(Loan_Amount_Disbursed),
    MAX(Loan_Amount_Disbursed),
    MIN(Bank_Approved_Amount),
    MAX(Bank_Approved_Amount)
FROM sba_data; 

-- By sector
SELECT
	SECTOR,
    MIN(Loan_Amount_Disbursed),
    MAX(Loan_Amount_Disbursed),
    MIN(Bank_Approved_Amount),
    MAX(Bank_Approved_Amount)
FROM sba_data
GROUP BY SECTOR
ORDER BY MAX(Loan_Amount_Disbursed) DESC;


SELECT
    Loan_Status,
    COUNT(*) AS Total_Loans,
    ROUND(AVG(Loan_Amount_Disbursed - Bank_Approved_Amount),2) AS Avg_Difference
FROM sba_data
WHERE Loan_Amount_Disbursed > Bank_Approved_Amount
GROUP BY Loan_Status;



SELECT
    ROUND(AVG(Loan_Amount_Disbursed / Bank_Approved_Amount),2) AS Avg_Ratio,
    MIN(Loan_Amount_Disbursed / Bank_Approved_Amount) AS Min_Ratio,
    MAX(Loan_Amount_Disbursed / Bank_Approved_Amount) AS Max_Ratio
FROM sba_data
WHERE Loan_Amount_Disbursed > Bank_Approved_Amount
AND Bank_Approved_Amount > 0;


SELECT 
	BANK_NAME,
    COUNT(BANK_NAME)
FROM SBA_DATA
WHERE LOAN_AMOUNT_DISBURSED > BANK_APPROVED_AMOUNT
GROUP BY BANK_NAME
ORDER BY COUNT(BANK_NAME) DESC;


SELECT
    Bank_Name,
    COUNT(*) AS Total_Loans,
    SUM(CASE
            WHEN Loan_Amount_Disbursed > Bank_Approved_Amount THEN 1
            ELSE 0
        END) AS Greater_Cases,
    ROUND(
        SUM(CASE
                WHEN Loan_Amount_Disbursed > Bank_Approved_Amount THEN 1
                ELSE 0
            END) * 100.0 / COUNT(*),
        2
    ) AS Percentage
FROM sba_data
GROUP BY Bank_Name
HAVING COUNT(*) >= 500
ORDER BY Percentage DESC;


-- Top 5 States by Loan amount disbursed
SELECT 
	STATE_NAME, 
    SUM(LOAN_AMOUNT_DISBURSED) as TOTAL_LOAN_AMOUNT
FROM SBA_DATA
GROUP BY STATE_NAME
ORDER BY SUM(LOAN_AMOUNT_DISBURSED) DESC
LIMIT 5;

-- TOP 10 Sectors with most loans borrowed.

SELECT
	SECTOR,
    STATE,
    COUNT(LOAN_ID) AS TOTAL_LOANS,
	COUNT(*)*100/SUM(COUNT(*)) OVER() AS percent_of_total_loans
FROM SBA_DATA
GROUP BY SECTOR, STATE
ORDER BY PERCENT_OF_TOTAL_LOANS DESC
LIMIT 10;

-- Top 5 sectors by: Total Loan Amount Disbursed

SELECT 
	SECTOR,
    SUM(LOAN_AMOUNT_DISBURSED) AS TOTAL_LOAN_AMOUNT
FROM SBA_DATA
GROUP BY SECTOR
ORDER BY SUM(LOAN_AMOUNT_DISBURSED) DESC
LIMIT 5;


-- Top 7 sectors with the highest: Total Charged-Off Principal
-- The reason for Top 7 is because there were Sectors in top 5 like (Unknown Industry and Other services) which did not gave enough insight, so had to increase it to 7
SELECT
	SECTOR,
    SUM(Charged_Off_Principal) AS Total_Charged_off_principal
FROM SBA_DATA
GROUP BY SECTOR
ORDER BY SUM(Charged_Off_Principal) DESC
LIMIT 7;


-- Top 15 banks by: Number of loans approved

SELECT COUNT(DISTINCT BANK_NAME) FROM SBA_DATA;

SELECT
	BANK_NAME,
    COUNT(Loan_ID) AS Total_approved_loans
FROM SBA_DATA
GROUP BY BANK_NAME
ORDER BY COUNT(Loan_ID) DESC
LIMIT 15;


-- Top 10 banks by: Total Bank Approved Amount

SELECT 
	BANK_NAME,
	SUM(BANK_APPROVED_AMOUNT) AS TOTAL_APPROVED_AMOUNT
FROM SBA_DATA
GROUP BY BANK_NAME
ORDER BY SUM(BANK_APPROVED_AMOUNT) DESC
LIMIT 10;
	

-- Average Loan Size - Sector Wise

SELECT
	SECTOR,
    ROUND(AVG(BANK_APPROVED_AMOUNT),2) AS AVERGAE_AMOUNT
FROM SBA_DATA
GROUP BY SECTOR;


-- Top 5 Sectors with Average SBA guarantee percentage

SELECT 
	SECTOR,
    ROUND(AVG(SBA_PERCENT) *100,2) AS AVERAGE_SBA_COVERAGE
FROM SBA_DATA
GROUP BY SECTOR
HAVING COUNT(LOAN_ID) > 1000
ORDER BY AVG(SBA_PERCENT) DESC
LIMIT 5;


-- Bottom 5 Sectors with Average SBA guarantee percentage
SELECT 
	SECTOR,
    ROUND(AVG(SBA_PERCENT) *100,2) AS AVERAGE_SBA_COVERAGE
FROM SBA_DATA
GROUP BY SECTOR
HAVING COUNT(LOAN_ID) > 1000
ORDER BY AVG(SBA_PERCENT) ASC
LIMIT 5;

-- Average loan amount for each Employee_Category

SELECT 
	EMPLOYEE_CATEGORY,
    ROUND(AVG(Bank_Approved_Amount),2) AS AVG_LOAN_AMOUNT
FROM SBA_DATA
GROUP BY EMPLOYEE_CATEGORY
ORDER BY ROUND(AVG(Bank_Approved_Amount),2) DESC;

-- Creating a view for Default Rate
CREATE VIEW CHECK_DEFAULT AS
SELECT
    *,
    CASE
        WHEN LOAN_STATUS = 'DEFAULTED' THEN 1
        ELSE 0
    END AS IS_DEFAULT,
	
FROM SBA_DATA;

-- Creating a view for Loss Rate


-- Which employee_category sector wise has the most default rate

SELECT
    CONCAT(SECTOR, ' | ', EMPLOYEE_CATEGORY) AS COMPANY_INFO,
    COUNT(LOAN_ID) AS TOTAL_LOANS,
    SUM(IS_DEFAULT) AS TOTAL_DEFAULTED_LOANS,
    ROUND(
        SUM(IS_DEFAULT) / COUNT(LOAN_ID) * 100,
        2
    ) AS DEFAULT_RATE
FROM CHECK_DEFAULT
GROUP BY SECTOR, EMPLOYEE_CATEGORY
HAVING COUNT(LOAN_ID) > 1000
ORDER BY DEFAULT_RATE DESC
LIMIT 10;


-- Top 3 Employee_category in every sector with highest default rate

WITH EMPLOYEE_RISK AS
(
    SELECT
        SECTOR,
        EMPLOYEE_CATEGORY,
        ROUND(
		SUM(IS_DEFAULT) / COUNT(LOAN_ID) * 100,
		2
		) AS DEFAULT_RATE
    FROM CHECK_DEFAULT
    GROUP BY SECTOR, EMPLOYEE_CATEGORY
    HAVING COUNT(*) >= 1000
)
SELECT *
FROM
(
    SELECT *,
           RANK() OVER(
               PARTITION BY SECTOR
               ORDER BY DEFAULT_RATE DESC
           ) AS RANKINGS
    FROM EMPLOYEE_RISK
) X
WHERE RANKINGS <= 3;

    


-- Average Loan Amount
-- Average SBA %
-- Average Charged-Off Principal
-- Loan_Term_Category wise

SELECT
	LOAN_CATEGORY,
    COUNT(LOAN_ID) AS total_loans,
    ROUND(AVG(Loan_amount_disbursed),2) as Average_Loan_Amount,
    ROUND(AVG((SBA_PERCENT) * 100),2) as Average_SBA_percent,
    ROUND(AVG(CHARGED_OFF_PRINCIPAL),2) as Average_Charged_Off_Principal
FROM SBA_DATA
GROUP BY LOAN_CATEGORY
ORDER BY LOAN_CATEGORY;




-- Phase 2 – Business & Risk Analysis

-- Top 10 Combination of Sector and Business_Type has the highest default rate and Lowest default rates?	

SELECT 
	SECTOR,
    BUSINESS_TYPE,
    ROUND(SUM(
		IS_DEFAULT
    )/COUNT(*)*100,2) AS DEFAULT_RATE
FROM CHECK_DEFAULT
GROUP BY SECTOR, BUSINESS_TYPE
HAVING COUNT(LOAN_ID) > 1000
ORDER BY ROUND(SUM(
		CASE WHEN LOAN_STATUS = 'DEFAULTED' THEN 1 ELSE 0 END
    )/COUNT(*)*100,2) ASC -- DESC
LIMIT 10;


-- Which Loan_Category has the highest default rate?

SELECT 
	LOAN_CATEGORY,
    ROUND(SUM(
		IS_DEFAULT
    )/COUNT(*)*100,2) AS HIGH_DEFAULT_RATE
FROM CHECK_DEFAULT
GROUP BY LOAN_CATEGORY
ORDER BY HIGH_DEFAULT_RATE DESC;


-- Does SBA coverage influence defaults?

SELECT 
	SBA_COVERAGE_CATEGORY,
    COUNT(*) AS TOTAL_LOANS,
    ROUND(SUM(
		IS_DEFAULT
    )/COUNT(*)*100,2) AS HIGH_DEFAULT_RATE,
    ROUND(AVG(CHARGED_OFF_PRINCIPAL),2) AS Average_charged_off_principal
FROM CHECK_DEFAULT
GROUP BY SBA_COVERAGE_CATEGORY
ORDER BY TOTAL_LOANS;


-- Top 10 State–Sector combinations with the highest charged-off principal.
SELECT
	CONCAT(STATE_NAME,' | ',SECTOR) AS STATE_SECTOR_INFO,
    ROUND(SUM(
		IS_DEFAULT
    )/COUNT(*)*100,2) AS HIGH_DEFAULT_RATE
FROM CHECK_DEFAULT
GROUP BY STATE_NAME, SECTOR
HAVING COUNT(LOAN_ID) > 1000
ORDER BY HIGH_DEFAULT_RATE DESC
LIMIT 10;



-- Top 10 Banks with at least 1000 loans, which banks have the highest and lowest default rates?

SELECT
	BANK_NAME,
    COUNT(LOAN_ID) AS LOAN_COUNT,
    ROUND(SUM(
		IS_DEFAULT
    )/COUNT(*)*100,2) AS LOW_DEFAULT_RATE
FROM CHECK_DEFAULT
GROUP BY BANK_NAME
HAVING COUNT(LOAN_ID) > 1000
ORDER BY LOW_DEFAULT_RATE ASC  -- DESC
LIMIT 10;



-- Does loan term affect risk?

SELECT 
	LOAN_TERM_CATEGORY,
    ROUND(SUM(IS_DEFAULT)/COUNT(*)*100,2) AS DEFAULT_RATE,
	ROUND(AVG(BANK_APPROVED_AMOUNT),2) AS AVERAGE_LOAN_AMOUNT,
    ROUND(AVG(CHARGED_OFF_PRINCIPAL),2) AS Average_Charged_Off_Principal
FROM CHECK_DEFAULT
GROUP BY LOAN_TERM_CATEGORY
ORDER BY DEFAULT_RATE DESC;


-- Which Employee Category receives the largest loans but has the lowest default rate?

SELECT
	EMPLOYEE_CATEGORY,
    ROUND(AVG(BANK_APPROVED_AMOUNT),2) AS AVERAGE_LOAN,
    ROUND(SUM(
		IS_DEFAULT
    )/COUNT(*)*100,2) AS DEFAULT_RATE
FROM CHECK_DEFAULT
GROUP BY EMPLOYEE_CATEGORY
ORDER BY AVERAGE_LOAN DESC, DEFAULT_RATE ASC;



-- Top 10 sectors with highest default rate in new business only

SELECT
    SECTOR,
    ROUND(SUM(IS_DEFAULT)/COUNT(*)*100,2) AS DEFAULT_RATE
FROM CHECK_DEFAULT
WHERE BUSINESS_TYPE = 'NEW'
GROUP BY SECTOR
HAVING COUNT(LOAN_ID) >1000
ORDER BY DEFAULT_RATE DESC
LIMIT 10;
    
-- Top 10 sectors with highest default rate in existing business only

SELECT
    SECTOR,
    ROUND(SUM(IS_DEFAULT)/COUNT(*)*100,2) AS DEFAULT_RATE
FROM CHECK_DEFAULT
WHERE BUSINESS_TYPE = 'EXISTING'
GROUP BY SECTOR
HAVING COUNT(LOAN_ID) >1000
ORDER BY DEFAULT_RATE DESC
LIMIT 10;



-- default rate by employee category.

SELECT 
	EMPLOYEE_CATEGORY,
    COUNT(LOAN_ID) AS TOTAL_LOANS_TAKEN,
    SUM(IS_DEFAULT)  AS TOTAL_DEFAULTED_LOANS,
    ROUND(SUM(IS_DEFAULT)/COUNT(*)*100,2) AS DEFAULT_RATE
FROM CHECK_DEFAULT
GROUP BY EMPLOYEE_CATEGORY
ORDER BY DEFAULT_RATE DESC;


-- Default rate by business type

SELECT 
	BUSINESS_TYPE,
    COUNT(*) AS TOTAL_LOANS_TAKEN,
    SUM(IS_DEFAULT)  AS TOTAL_DEFAULTED_LOANS,
    ROUND(SUM(IS_DEFAULT)/COUNT(*)*100,2) AS DEFAULT_RATE
FROM CHECK_DEFAULT
GROUP BY BUSINESS_TYPE
ORDER BY DEFAULT_RATE DESC;



-- Case – Executive Dashboard Queries

-- 1. Portfolio Health
SELECT 
	COUNT(*) AS TOTAL_LOANS,
    SUM(
     IS_DEFAULT
    ) AS TOTAL_DEFAULT_LOANS,
    ROUND(SUM(
			IS_DEFAULT
    )/COUNT(*)*100,2) AS OVERALL_DEFAULT_RATE,
    sum(BANK_APPROVED_AMOUNT) AS TOTAL_LOAN_VALUE,
    SUM(CHARGED_OFF_PRINCIPAL) AS TOTAL_CHARGED_OFF_PRINCIPAL,
    ROUND(AVG(SBA_PERCENT)*100,2) AS Average_SBA_PERCENT
FROM CHECK_DEFAULT;


-- Largest sector

SELECT 
	SECTOR,
    SUM(BANK_APPROVED_AMOUNT) AS TOTAL_LOAN
FROM SBA_DATA
WHERE SECTOR<>'Unknown Industry'
GROUP BY SECTOR
ORDER BY TOTAL_LOAN DESC;
                        -- first largest sector was Unknown Industry so had to exclude it in the analysis


-- Largest State

SELECT 
	STATE_NAME,
    SUM(BANK_APPROVED_AMOUNT) AS TOTAL_LOAN
FROM SBA_DATA
GROUP BY STATE_NAME
ORDER BY TOTAL_LOAN DESC
LIMIT 1;


-- Largest Bank

SELECT 
	BANK_NAME,
    SUM(BANK_APPROVED_AMOUNT) AS TOTAL_LOAN
FROM SBA_DATA
GROUP BY BANK_NAME
ORDER BY TOTAL_LOAN DESC
LIMIT 1;



-- Top 10 Bank's portfolio

SELECT 
	BANK_NAME,
    COUNT(*) AS TOTAL_LOANS,
    ROUND(SUM(
		IS_DEFAULT
    )/COUNT(*)*100,2) AS DEFAULT_RATE,
    ROUND(AVG(BANK_APPROVED_AMOUNT),2) AS Average_loan,
    SUM(CHARGED_OFF_PRINCIPAL) AS Total_charged_off_principal
FROM CHECK_DEFAULT
GROUP BY BANK_NAME
ORDER BY TOTAL_LOANS DESC, DEFAULT_RATE DESC
LIMIT 10;


-- Bank Performance

SELECT * FROM SBA_DATA;	

WITH BANK_PERFORMANCE_CTE AS (
	SELECT
		BANK_NAME,
        COUNT(LOAN_ID) AS TOTAL_LOAN,
        ROUND(
			SUM(
				IS_DEFAULT
				)/COUNT(*)*100,
					2) AS DEFAULT_RATE,
		ROUND(
			SUM(CHARGED_OFF_PRINCIPAL)
				/SUM(LOAN_AMOUNT_DISBURSED)*100,
					2) AS LOSS_RATE,
		COUNT(LOAN_ID) AS TOTAL_LOANS
		FROM CHECK_DEFAULT
        GROUP BY BANK_NAME
),
BANK_STATS AS (
	SELECT
		AVG(DEFAULT_RATE) AS AVG_DEFAULT_RATE,
        AVG(LOSS_RATE) AS AVG_LOSS_RATE
	FROM BANK_PERFORMANCE_CTE
    WHERE TOTAL_LOANS >= 1000
)
SELECT
	B.*,
    CASE
		WHEN A.AVG_DEFAULT_RATE > B.DEFAULT_RATE AND A.AVG_LOSS_RATE > B.LOSS_RATE THEN 'Excellent'
        WHEN A.AVG_DEFAULT_RATE < B.DEFAULT_RATE AND A.AVG_LOSS_RATE < B.LOSS_RATE THEN 'Needs Improvement'
        ELSE 'Good'
	END AS PERFORMANCE
FROM BANK_PERFORMANCE_CTE B
CROSS JOIN BANK_STATS A
WHERE B.TOTAL_LOANS >= 1000
ORDER BY DEFAULT_RATE DESC;
	
-- FROM BANK_PERFORMANCE_CTE B
-- CROSS JOIN BANK_STATS A
-- WHERE TOTAL_LOAN >= 1000
-- ORDER BY LOSS_RATE DESC;







-- SELECT
-- 	AVG(DEFAULT_RATE)
-- FROM BANK_PERFORMANCE_CTE;

-- SELECT 
-- 	AVG(LOSS_RATE)
-- FROM BANK_PERFORMANCE_CTE;


-- SELECT 
-- 	BANK_NAME, 
-- 	DEFAULT_RATE, 
--     LOSS_RATE
-- FROM BANK_PERFORMANCE_CTE
-- WHERE TOTAL_LOAN > 1000
-- ORDER BY LOSS_RATE DESC;



-- Ranking Analysis


-- Universal CTE for Bank to Sector Analysis
WITH BANK_SECTOR_RISK AS
(
    SELECT
        BANK_NAME,
        SECTOR,

        COUNT(*) AS TOTAL_LOAN_COUNT,

        SUM(
            IS_DEFAULT
        ) AS DEFAULTED_COUNT,

        ROUND(
            SUM(
                IS_DEFAULT
            ) * 100.0 / COUNT(*),
            2
        ) AS DEFAULT_RATE

    FROM CHECK_DEFAULT
    GROUP BY BANK_NAME, SECTOR
    HAVING COUNT(*) >= 100
)

-- 1. Top 3 Risky Sectors
SELECT *
FROM
(
    SELECT *,
           ROW_NUMBER() OVER(
               PARTITION BY BANK_NAME
               ORDER BY DEFAULT_RATE DESC
           ) AS SECTOR_RANK
    FROM BANK_SECTOR_RISK
) X
WHERE SECTOR_RANK <= 3
ORDER BY BANK_NAME, SECTOR_RANK;



-- Universal CTE - Bank to State Analysis

WITH BANK_STATE_RISK AS
(
    SELECT
        BANK_NAME,
        STATE_NAME,

        COUNT(*) AS TOTAL_LOAN_COUNT,

        SUM(
            IS_DEFAULT
        ) AS DEFAULTED_COUNT,

        ROUND(
            SUM(
                IS_DEFAULT
            ) * 100.0 / COUNT(*),
            2
        ) AS DEFAULT_RATE

    FROM CHECK_DEFAULT
    GROUP BY BANK_NAME, STATE_NAME
    HAVING COUNT(*) >= 100
)

-- 1. Top 3 Risky States
-- SELECT *
-- FROM
-- (
--     SELECT *,
--            ROW_NUMBER() OVER(
--                PARTITION BY BANK_NAME
--                ORDER BY DEFAULT_RATE DESC
--            ) AS STATE_RANK
--     FROM BANK_STATE_RISK
-- ) X
-- WHERE STATE_RANK <= 3
-- ORDER BY BANK_NAME, STATE_RANK;


-- 2. Top 5 risky banks in every state

SELECT *
FROM (
	SELECT *,
    ROW_NUMBER() OVER(PARTITION BY STATE_NAME ORDER BY DEFAULT_RATE DESC) AS BANK_DEFAULT_RATE
    FROM BANK_STATE_RISK
) X
WHERE BANK_DEFAULT_RATE <=5
ORDER BY STATE_NAME;

    

-- State Performance Scorecard
-- Default rate, Loss rate, Average Loan State wise

WITH STATE_PERFORMANCE AS(
SELECT
	STATE_NAME,
    COUNT(LOAN_ID) AS TOTAL_LOANS,
    ROUND(SUM(IS_DEFAULT)/COUNT(*)*100,2) AS DEFAULT_RATE,
	ROUND((SUM(CHARGED_OFF_PRINCIPAL)/SUM(LOAN_AMOUNT_DISBURSED))*100,2) AS LOSS_RATE,
    ROUND(AVG(LOAN_AMOUNT_DISBURSED),2) AS AVERAGE_LOAN
FROM CHECK_DEFAULT
GROUP BY STATE_NAME
ORDER BY DEFAULT_RATE DESC, LOSS_RATE DESC
),
AVG_RATES AS(
SELECT
	AVG(DEFAULT_RATE) AS AVERAGE_DEFAULT_RATE,
    AVG(LOSS_RATE) AS AVERAGE_LOSS_RATE
FROM STATE_PERFORMANCE
),
PERFORMANCE_CTE AS(
SELECT 
	S.*,
    CASE
		WHEN DEFAULT_RATE < AVERAGE_DEFAULT_RATE AND LOSS_RATE < AVERAGE_LOSS_RATE THEN 'EXCELLENT'
        WHEN DEFAULT_RATE > AVERAGE_DEFAULT_RATE AND LOSS_RATE >AVERAGE_LOSS_RATE THEN 'Needs Improvement'
        ELSE 'Mixed Performance'
	END AS PERFORMANCE
FROM STATE_PERFORMANCE S
CROSS JOIN AVG_RATES
ORDER BY DEFAULT_RATE DESC)

SELECT * FROM PERFORMANCE_CTE
WHERE PERFORMANCE =  'Mixed Performance';      -- 'Excellent';   -- 'Needs Improvement';



-- Sector Perfromance Card
-- Default rate, Loss rate, Average Loan State wise

WITH SECTOR_PERFORMANCE AS (
SELECT
	SECTOR,
    COUNT(LOAN_ID) AS TOTAL_LOANS,
    ROUND(SUM(IS_DEFAULT)/COUNT(*)*100,2) AS DEFAULT_RATE,
	ROUND((SUM(CHARGED_OFF_PRINCIPAL)/SUM(LOAN_AMOUNT_DISBURSED))*100,2) AS LOSS_RATE,
    ROUND(AVG(LOAN_AMOUNT_DISBURSED),2) AS AVERAGE_LOAN
FROM CHECK_DEFAULT
GROUP BY SECTOR
ORDER BY DEFAULT_RATE DESC, LOSS_RATE DESC
),
AVG_RATES AS(
SELECT
	AVG(DEFAULT_RATE) AS AVERAGE_DEFAULT_RATE,
    AVG(LOSS_RATE) AS AVERAGE_LOSS_RATE
FROM SECTOR_PERFORMANCE
),
PERFORMANCE_CTE AS (SELECT 
	S.*,
    CASE
		WHEN DEFAULT_RATE < AVERAGE_DEFAULT_RATE AND LOSS_RATE < AVERAGE_LOSS_RATE THEN 'EXCELLENT'
        WHEN DEFAULT_RATE > AVERAGE_DEFAULT_RATE AND LOSS_RATE >AVERAGE_LOSS_RATE THEN 'Needs Improvement'
        ELSE 'Mixed Performance'
	END AS PERFORMANCE
FROM SECTOR_PERFORMANCE S
CROSS JOIN AVG_RATES
ORDER BY DEFAULT_RATE DESC)

SELECT * FROM PERFORMANCE_CTE
WHERE PERFORMANCE = 'Mixed Performance';    -- 'Excellent';  -- 'Needs Improvement';


-- Employee Risk Matrix
WITH EMPLOYEES_RISK AS(
SELECT
	EMPLOYEE_CATEGORY,
    ROUND(AVG(LOAN_AMOUNT_DISBURSED),2) AS AVERAGE_LOAN,
    ROUND(SUM(IS_DEFAULT)/COUNT(*)*100,2) AS DEFAULT_RATE,
	ROUND((SUM(CHARGED_OFF_PRINCIPAL)/SUM(LOAN_AMOUNT_DISBURSED))*100,2) AS LOSS_RATE
FROM CHECK_DEFAULT
GROUP BY EMPLOYEE_CATEGORY
),
SECOND_EMPLOYEES AS(
	SELECT 
		AVG(DEFAULT_RATE) AS AVERAGE_DEFAULTS,
        AVG(LOSS_RATE) AS AVERAGE_LOSS
	FROM EMPLOYEES_RISK
)
SELECT E.*,
	CASE 
		WHEN DEFAULT_RATE < AVERAGE_DEFAULTS AND LOSS_RATE < AVERAGE_LOSS THEN 'LOW RISK'
        WHEN DEFAULT_RATE > AVERAGE_DEFAULTS AND LOSS_RATE > AVERAGE_LOSS THEN 'HIGH RISK'
        ELSE 'MEDIUM RISK'
	END AS EMPLOYEE_RISK_CLASSIFICATION
FROM EMPLOYEES_RISK E
CROSS JOIN SECOND_EMPLOYEES
ORDER BY E.DEFAULT_RATE desc;



-- Business Type Dashboard

SELECT DISTINCT BUSINESS_TYPE FROM SBA_DATA;

SELECT
	BUSINESS_TYPE,
	ROUND(SUM(IS_DEFAULT)/COUNT(*)*100,2) AS DEFAULT_RATE,
	ROUND((SUM(CHARGED_OFF_PRINCIPAL)/SUM(LOAN_AMOUNT_DISBURSED))*100,2) AS LOSS_RATE,
    ROUND(AVG(LOAN_AMOUNT_DISBURSED),2) AS AVERAGE_LOAN,
    ROUND(AVG(SBA_PERCENT)*100,2) AS SBA_COVERAGE_ON_AVERAGE,
    SUM(CHARGED_OFF_PRINCIPAL) AS AVERAGE_CHARGED_OFF_AMOUNT
FROM CHECK_DEFAULT
GROUP BY BUSINESS_TYPE;



-- Sector Ranking by Risk
-- Sector with highest risk will be ranked 1st and followed by others below

WITH EXECUTIVE_RANKING AS (
SELECT
	SECTOR,
    ROUND(SUM(IS_DEFAULT)/COUNT(*)*100,2) AS DEFAULT_RATE,
	ROUND((SUM(CHARGED_OFF_PRINCIPAL)/SUM(LOAN_AMOUNT_DISBURSED))*100,2) AS LOSS_RATE
    FROM CHECK_DEFAULT
    GROUP BY SECTOR
)
SELECT *
FROM (
	SELECT *,
    RANK() OVER(ORDER BY DEFAULT_RATE DESC, LOSS_RATE DESC) AS SECTOR_RANKING
    FROM EXECUTIVE_RANKING
    LIMIT 10
) X;



-- Customer Persona Analysis

SELECT
	CONCAT(
    BUSINESS_TYPE,
    ' | ',
    EMPLOYEE_CATEGORY,
    ' | ',
    SECTOR
	) AS CUSTOMER_PERSONA,
    COUNT(LOAN_ID) AS TOTAL_LOAN,
    ROUND(AVG(BANK_APPROVED_AMOUNT),2) AS AVG_LOAN,
    ROUND(SUM(IS_DEFAULT)/COUNT(*)*100,2) AS DEFAULT_RATE,
	ROUND((SUM(CHARGED_OFF_PRINCIPAL)/SUM(LOAN_AMOUNT_DISBURSED))*100,2) AS LOSS_RATE
FROM CHECK_DEFAULT
GROUP BY SECTOR, EMPLOYEE_CATEGORY, BUSINESS_TYPE
HAVING COUNT(LOAN_ID) >= 1000
ORDER BY DEFAULT_RATE ASC, LOSS_RATE ASC    -- DESC, LOSS_RATE DESC
LIMIT 10;


-- Time Series / Date Analysis - Data conversion process

-- Portfolio Growth Over Time
SELECT
	YEAR(str_to_date(DISBURSEMENT_DATE, '%d-%b-%y')) AS YEARS,
	COUNT(*) AS NUMBER_OF_LOANS,
    SUM(LOAN_AMOUNT_DISBURSED) AS TOTAL_LOAN_AMOUNT
FROM SBA_DATA
GROUP BY YEARS
ORDER BY NUMBER_OF_LOANS DESC, TOTAL_LOAN_AMOUNT DESC;

-- Found date column is in text data type also found 6 issue in loans they were disbursed on 2066, 2068, 2069 alerting a date conversion issue in str_to_date function.

SELECT
    Loan_ID,
    YEAR(str_to_date(Disbursement_Date, '%d-%b-%y')) AS DIS_YEARS,
    Approval_Date,
    Approval_Fiscal_Year
FROM sba_data
WHERE YEAR(str_to_date(Disbursement_Date, '%d-%b-%y')) > YEAR(CURDATE());


-- New column creation for conversion to date datatype
ALTER TABLE SBA_DATA
ADD COLUMN DISBURSEMENT_DATE_NEW DATE;

-- To find whether blank exists in the column
SELECT DISBURSEMENT_DATE
FROM SBA_DATA
WHERE DISBURSEMENT_DATE IS NOT NULL
AND STR_TO_DATE(TRIM(DISBURSEMENT_DATE), '%d-%b-%y') IS NULL;


SELECT COUNT(*)
FROM SBA_DATA
WHERE DISBURSEMENT_DATE IS NULL;

SELECT COUNT(*)
FROM SBA_DATA
WHERE DISBURSEMENT_DATE = '';

UPDATE SBA_DATA
SET DISBURSEMENT_DATE_NEW =
    STR_TO_DATE(TRIM(DISBURSEMENT_DATE), '%d-%b-%y')
WHERE TRIM(DISBURSEMENT_DATE) <> '';


-- Handling 2066, 2068, 2069 date value
UPDATE SBA_DATA
SET DISBURSEMENT_DATE_NEW = date_sub(DISBURSEMENT_DATE_NEW, INTERVAL 100 YEAR)
WHERE YEAR(DISBURSEMENT_DATE_NEW) BETWEEN 2066 AND 2069;

SELECT DISTINCT YEAR(DISBURSEMENT_DATE_NEW) FROM SBA_DATA
ORDER BY YEAR(DISBURSEMENT_DATE_NEW);

-- Found NULLS exists
SELECT COUNT(*) FROM SBA_DATA
WHERE DISBURSEMENT_DATE_NEW IS NULL;

-- DISBURSEMENT DATE NEW COLUMN ready for analysis

-- Converting default date similarly

describe SBA_DATA;

SELECT
	COUNT(*)
FROM SBA_DATA
WHERE DEFAULT_DATE  IS NOT NULL;

-- FOUND NO NULLS EXIST, NOW CHECKING FOR BLANKS

SELECT
	COUNT(*)
FROM SBA_DATA
WHERE DEFAULT_DATE = '';


ALTER TABLE SBA_DATA
ADD COLUMN DEFAULT_DATE_NEW DATE;

UPDATE SBA_DATA
SET DEFAULT_DATE_NEW = str_to_date(DEFAULT_DATE, '%d-%b-%y')
WHERE DEFAULT_DATE <> '';


SELECT COUNT(*) FROM SBA_DATA
WHERE DEFAULT_DATE_NEW IS NULL;

SELECT COUNT(*) FROM SBA_DATA
WHERE TRIM(DEFAULT_DATE_NEW)  = '';

SELECT DISTINCT YEAR(DEFAULT_DATE_NEW) FROM SBA_DATA
ORDER BY YEAR(DEFAULT_DATE_NEW);



-- Conversion of Approval date

SELECT
	COUNT(*)
FROM SBA_DATA
WHERE APPROVAL_DATE  IS NOT NULL;

ALTER TABLE SBA_DATA
ADD COLUMN APPROVAL_DATE_NEW DATE;

UPDATE SBA_DATA
SET APPROVAL_DATE_NEW = str_to_date(APPROVAL_DATE, '%d-%m-%Y')
WHERE APPROVAL_DATE <> '';


SELECT  DISTINCT YEAR(APPROVAL_DATE_NEW) FROM SBA_DATA
ORDER BY YEAR(APPROVAL_DATE_NEW);


-- SBA TIME SERIES ANALYSIS

-- How has the SBA loan portfolio grown over the years?

SELECT
	YEAR(DISBURSEMENT_DATE_NEW) AS YEARS,
    COUNT(*) AS TOTAL_LOANS,
    SUM(LOAN_AMOUNT_DISBURSED) AS TOTAL_AMOUNT
FROM SBA_DATA
GROUP BY YEARS
ORDER BY TOTAL_LOANS DESC, TOTAL_AMOUNT DESC;



-- Year that recorded the highest default rate
-- OUT OF MINIMUM 100 LOANS
SELECT
	YEAR(DISBURSEMENT_DATE_NEW) AS MAX_DEFAULT_YEAR,
    ROUND(SUM(IS_DEFAULT)/COUNT(*)*100,2) AS DEFAULT_RATE
FROM CHECK_DEFAULT
GROUP BY MAX_DEFAULT_YEAR
HAVING COUNT(LOAN_ID) >= 100
ORDER BY DEFAULT_RATE DESC
LIMIT 5;


-- -- OUT OF MINIMUM 1000 LOANS
SELECT
	YEAR(DISBURSEMENT_DATE_NEW) AS MAX_DEFAULT_YEAR,
    ROUND(SUM(IS_DEFAULT)/COUNT(*)*100,2) AS DEFAULT_RATE
FROM CHECK_DEFAULT
GROUP BY MAX_DEFAULT_YEAR
HAVING COUNT(LOAN_ID) >= 1000
ORDER BY DEFAULT_RATE DESC
LIMIT 5;


-- Did the average loan amount changed over time?
-- Average Approved Loan
SELECT
	YEAR(APPROVAL_DATE_NEW) AS APPROVAL_DATE,
	ROUND(AVG(BANK_APPROVED_AMOUNT),2) as AVG_LOAN_AMOUNT
FROM SBA_DATA
GROUP BY YEAR(APPROVAL_DATE_NEW)
ORDER BY YEAR(APPROVAL_DATE_NEW);


-- Average Disbursed Loan

SELECT
	YEAR(DISBURSEMENT_DATE_NEW) AS DISBURSED_DATE,
	ROUND(AVG(LOAN_AMOUNT_DISBURSED),2) AS AVG_LOAN_AMOUNT
FROM SBA_DATA
GROUP BY YEAR(DISBURSEMENT_DATE_NEW)
ORDER BY YEAR(DISBURSEMENT_DATE_NEW);


-- sectors that dominated SBA lending every year

WITH RANKEDSECTORS AS (
    SELECT 
        YEAR(DISBURSEMENT_DATE_NEW) AS YEARS, 
        SECTOR, 
        COUNT(LOAN_ID) AS TOTAL_LOAN,
        RANK() OVER (
            PARTITION BY YEAR(DISBURSEMENT_DATE_NEW) 
            ORDER BY COUNT(LOAN_ID) DESC
        ) AS RANKINGY
    FROM SBA_DATA 
    WHERE SECTOR <> 'UNKNOWN INDUSTRY'
    GROUP BY YEAR(DISBURSEMENT_DATE_NEW), SECTOR
)
SELECT RANKINGY, YEARS, SECTOR, TOTAL_LOAN
FROM RANKEDSECTORS
WHERE RANKINGY <= 5 AND YEARS IS NOT NULL
ORDER BY YEARS ASC, RANKINGY ASC;


-- sector ranking by total loan amount


WITH RANKEDSECTORS AS (
    SELECT 
        YEAR(DISBURSEMENT_DATE_NEW) AS YEARS, 
        SECTOR, 
        SUM(LOAN_AMOUNT_DISBURSED) AS TOTAL_LOAN_AMOUNT,
        RANK() OVER (
            PARTITION BY YEAR(DISBURSEMENT_DATE_NEW) 
            ORDER BY SUM(LOAN_AMOUNT_DISBURSED) DESC
        ) AS RANKING_BY_AMOUNT
    FROM SBA_DATA 
    WHERE SECTOR <> 'UNKNOWN INDUSTRY'
    GROUP BY YEAR(DISBURSEMENT_DATE_NEW), SECTOR
)
SELECT RANKING_BY_AMOUNT, YEARS, SECTOR, TOTAL_LOAN_AMOUNT
FROM RANKEDSECTORS
WHERE RANKING_BY_AMOUNT <= 5 AND YEARS IS NOT NULL
ORDER BY YEARS ASC, RANKING_BY_AMOUNT ASC;



-- Which banks expanded their SBA lending the most over time?

WITH RANKED_BANK_TOTAL_LOANS AS (
	SELECT
		RANK() OVER(PARTITION BY YEAR(DISBURSEMENT_DATE_NEW) ORDER BY COUNT(LOAN_ID) DESC) AS BANK_RANKS,
        YEAR(DISBURSEMENT_DATE_NEW) AS YEARS,
        COUNT(LOAN_ID) AS TOTAL_LOANS_LENT,
        BANK_NAME
	FROM SBA_DATA
    GROUP BY YEARS, BANK_NAME
)
SELECT * FROM RANKED_BANK_TOTAL_LOANS
WHERE YEARS IS NOT NULL AND BANK_RANKS <= 10;


-- Which years had the highest portfolio losses and riskiest customer portfolio?

SELECT
	YEAR(DISBURSEMENT_DATE_NEW) AS YEARS,
    SUM(CHARGED_OFF_PRINCIPAL) AS DEFAULT_AMOUNT,
    ROUND((SUM(CHARGED_OFF_PRINCIPAL)/SUM(LOAN_AMOUNT_DISBURSED))*100,2) AS LOSS_RATE
FROM SBA_DATA
GROUP BY YEARS
ORDER BY LOSS_RATE DESC;


-- Has SBA guarantee percentage changed over time?

SELECT
	YEAR(DISBURSEMENT_DATE_NEW) AS YEARS,
    ROUND(AVG(SBA_PERCENT) * 100,2) AS Average_SBA_Coverage
FROM SBA_DATA
GROUP BY YEARS
ORDER BY YEARS ASC;


-- Did new businesses receive more loans over time?

SELECT 
	YEAR(DISBURSEMENT_DATE_NEW) AS YEARS,
    BUSINESS_TYPE,
    COUNT(LOAN_ID) AS TOTAL_LOANS
FROM SBA_DATA
WHERE BUSINESS_TYPE = 'NEW'
GROUP BY YEARS, BUSINESS_TYPE;



-- Which month has the highest loan approvals

SELECT
	MONTHNAME(APPROVAL_DATE_NEW) AS APPROVAL_MONTHS,
    COUNT(LOAN_ID) AS TOTAL_LOANS,
    SUM(LOAN_AMOUNT_DISBURSED) AS TOTAL_LOAN_AMOUNT,
    ROUND(SUM(IS_DEFAULT)/COUNT(*)*100,2) AS DEFAULT_RATE
FROM CHECK_DEFAULT
GROUP BY MONTHNAME(APPROVAL_DATE_NEW)
ORDER BY TOTAL_LOANS DESC	;



-- Before vs After Financial Crisis 2008

SELECT
	CASE
		WHEN YEAR(APPROVAL_DATE_NEW) > 2008 THEN 'AFTER FINANCIAL CRISIS'
        WHEN YEAR(APPROVAL_DATE_NEW) = 2008 THEN 'FINANCIAL CRISIS YEAR'
        ELSE 'BEFORE FINANCIAL CRISIS'
	END AS PERIOD,
    COUNT(LOAN_ID) AS TOTAL_LOANS,
    SUM(LOAN_AMOUNT_DISBURSED) AS TOTAL_LOAN_AMOUNT,
    AVG(LOAN_AMOUNT_DISBURSED) AS AVERAGE_LOAN_AMOUNT,
    ROUND(SUM(IS_DEFAULT)
            /
            COUNT(*)*100,2) AS DEFAULT_RATE,
	ROUND(SUM(CHARGED_OFF_PRINCIPAL)/SUM(LOAN_AMOUNT_DISBURSED)*100,2) AS LOSS_RATE,
    ROUND(AVG(SBA_PERCENT)*100,2) AS AVERAGE_SBA_PERCENT
FROM CHECK_DEFAULT
GROUP BY PERIOD;



